name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Get date
      id: get-date
      run: echo "::set-output name=date::$(date -u '+%Y%m%d')"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Install Android SDK
      run: |
        wget "https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip" -O commandlinetools.zip
        sudo mkdir -p /usr/local/lib/android/sdk
        sudo unzip commandlinetools.zip -d /usr/local/lib/android/sdk/cmdline-tools
        sudo /usr/local/lib/android/sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk --install "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk;21.3.6528147"

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/lib/android/sdk/cmdline-tools/tools/bin" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/lib/android/sdk/ndk/21.3.6528147" >> $GITHUB_ENV

    - name: Build with Buildozer
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk
        
