name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Date
      run: echo "DATE=`date`" >> $GITHUB_ENV

    - name: Cache Buildozer global directory
      uses: actions/cache@v2
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build with Buildozer
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-8-jdk unzip
        pip install --upgrade pip
        pip install Cython==0.29.21 virtualenv
        pip install kivy buildozer
        buildozer -v android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: bin/*.apk

    - name: Post Run actions/cache@v2
      if: always()
      uses: actions/cache@v2
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
          
