name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Date
      run: echo "DATE=`date`" >> $GITHUB_ENV

    - name: Cache Buildozer global directory
      uses: actions/cache@v2
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-8-jdk unzip wget libncurses5 libstdc++6
        pip install --upgrade pip
        pip install Cython==0.29.21 virtualenv
        pip install kivy buildozer
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip
        mkdir latest
        mv cmdline-tools/* latest/
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platforms;android-30" "build-tools;30.0.3" "platform-tools"

    - name: Build with Buildozer
      run: |
        buildozer -v android debug --log_level 2 || true

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: bin/*.apk

    - name: Upload Buildozer log
      uses: actions/upload-artifact@v2
      with:
        name: buildozer-log
        path: .buildozer/android/platform/build/dists/*/buildozer.log

    - name: Post Run actions/cache@v2
      if: always()
      uses: actions/cache@v2
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
