name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build --tag kivy-build .

    - name: Run Docker container
      run: |
        docker run --name kivy-build-container kivy-build

    - name: Copy APK from Docker container
      run: |
        docker cp kivy-build-container:/app/bin/. ./bin

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: bin/*.apk

    - name: Clean up
      run: |
        docker rm kivy-build-container
        docker rmi kivy-build
        
